# Generated by Django 3.0.7 on 2020-07-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('req_from', models.CharField(max_length=10)),
                ('req_to', models.CharField(max_length=10)),
            ],
        ),
    ]
