# Generated by Django 3.0.7 on 2020-07-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Done_Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('req_from', models.CharField(max_length=10)),
                ('req_to', models.CharField(max_length=10)),
                ('comments', models.TextField()),
                ('reviews_added', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pending_Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('req_from', models.CharField(max_length=10)),
                ('req_to', models.CharField(max_length=10)),
                ('comments', models.TextField()),
            ],
        ),
    ]
