# Generated by Django 3.0.7 on 2020-07-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0003_auto_20200707_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='done_requests',
            name='reviews_added',
            field=models.TextField(default='this is the review'),
            preserve_default=False,
        ),
    ]
